# Generated by Django 5.0.6 on 2024-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq_feedback_faqtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
